data_dir: /data-net/storage/datasets/

# Train
batch_size: 2
max_pages: 2
gradient_accumulation_steps: 10
n_iterations: 10000
save_every: 1000
mixed_precision: 'bf16'

# Optimizer and Scheduler
lr: 0.0002
scheduler_name: linear
warmup_ratio: 0.1

# Eval
eval: true
eval_batch_size: 2
eval_max_pages: 20
eval_start: false

# Saving
only_keep_best: true
save_dir: save
project_name: CVPR
save_answers: false



